### ISSUE TITLE
wacatac.b ml Trojan

### ISSUE THREAD

**Issue by NRux** [Sxela/WarpFusion#42]
I just installed the latest version and my system found a Trojan in the files being installed.

**Comment by Sxela** [comment]
Which files?

сб, 18 февр. 2023 г. в 05:25, NRux ***@***.***>:

**Comment by NRux** [comment]
It's in the WarpFusion-0.1.0.zip

![Screenshot 2023-02-18 103606](https://user-images.githubusercontent.com/79342783/219883276-c3a00df2-b7fe-48f7-9a1a-362898d909ac.jpg)

**Comment by Sxela** [comment]
This archive doesn't even have executables, lol.
