### ISSUE TITLE
Click File -> Upload Notebook and upload the *.ipynb file  - cant find this file

### ISSUE THREAD

**Issue by eranmahalu** [Sxela/WarpFusion#43]
i cannot find this file:

Click File -> Upload Notebook and upload the *.ipynb file

where is the notebook?

**Comment by orinthesky** [comment]
Same here... I found a bunch of .ipynb files but which one is it?

**Comment by marcocanevadev** [comment]
i agree that part is not clear

**Comment by RobbyGraham** [comment]
SAME HERE - WHERE IS THIS?

**Comment by RobbyGraham** [comment]
iT IS REFERRING TO THE jUPITER BROWSER NOT THE GOOGLE COLAB

**Comment by marcocanevadev** [comment]
you get the ipynb file after subscribing to the author's patreon i reckon

**Comment by NiuDaVinci** [comment]
I DID SUBSCRIBED WITH 5 BUCKS to the patreon, where is the file?

**Comment by Pythonpa** [comment]
OK，It doesn't seem like a problem for me alone.....

**Comment by Sxela** [comment]
> I DID SUBSCRIBED WITH 5 BUCKS to the patreon, where is the file?

Look for an *.ipynb file attached to one of the latest posts available to you.
