### ISSUE TITLE
Unable to connect to the runtime

### ISSUE THREAD

**Issue by va1ngvarr** [Sxela/WarpFusion#50]
I have a GPU-server with Ubuntu 20.04. When i build and run container with `docker-compose up`, then i get something like http://localhost:8888/?token=41763aacd.. blah-blah. No any problems with run WarpFasion. But when i insert that link as Backend URL to "Local connection settings" in Google Colab i get error that:

> Unable to connect to the  runtime

Also somehow i cannot put external IP-address of my server instead of "localhost"
How do i solve this problem?

**Comment by Sxela** [comment]
Hi, you need to map remote url to the localhost:8888, like ```ssh <your server url> -p <your server port> -L 8888:localhost:8888```

**Comment by va1ngvarr** [comment]
> Hi, you need to map remote url to the localhost:8888, like `ssh <your server url> -p <your server port> -L 8888:localhost:8888`

Thank you very much :)
