### ISSUE TITLE
NameError: name 'hypernetwork' is not defined

### ISSUE THREAD

**Issue by arunrajan6600** [Sxela/WarpFusion#56]
Hi,
I am using  stable_warpfusion_v0_15_4.ipynb and getting this error in "Do the Run!" section. Any fix? Thank you

in <cell line: 567>:567                                                                          │
│ in do_run:1160                                                                                   │
│ in run_sd:1260                                                                                   │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/torch/autograd/grad_mode.py:27 in decorate_context       │
│                                                                                                  │
│    24 │   │   @functools.wraps(func)                                                             │
│    25 │   │   def decorate_context(*args, **kwargs):                                             │
│    26 │   │   │   with self.clone():                                                             │
│ ❱  27 │   │   │   │   return func(*args, **kwargs)                                               │
│    28 │   │   return cast(F, decorate_context)                                                   │
│    29 │                                                                                          │
│    30 │   def _wrap_generator(self, func):                                                       │
│                                                                                                  │
│ /content/k-diffusion/k_diffusion/sampling.py:128 in sample_euler                                 │
│                                                                                                  │
│   125 │   │   sigma_hat = sigmas[i] * (gamma + 1)                                                │
│   126 │   │   if gamma > 0:                                                                      │
│   127 │   │   │   x = x + eps * (sigma_hat ** 2 - sigmas[i] ** 2) ** 0.5                         │
│ ❱ 128 │   │   denoised = model(x, sigma_hat * s_in, **extra_args)                                │
│   129 │   │   d = to_d(x, sigma_hat, denoised)                                                   │
│   130 │   │   if callback is not None:                                                           │
│   131 │   │     x =  callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigma_hat, 'de   │
│ in model_fn:240                                                                                  │
│ in model_fn:228                                                                                  │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1194 in _call_impl            │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│ in forward:308                                                                                   │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1194 in _call_impl            │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /content/k-diffusion/k_diffusion/external.py:112 in forward                                      │
│                                                                                                  │
│   109 │                                                                                          │
│   110 │   def forward(self, input, sigma, **kwargs):                                             │
│   111 │   │   c_out, c_in = [utils.append_dims(x, input.ndim) for x in self.get_scalings(sigma   │
│ ❱ 112 │   │   eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)                 │
│   113 │   │   return input + eps * c_out                                                         │
│   114                                                                                            │
│   115                                                                                            │
│                                                                                                  │
│ /content/k-diffusion/k_diffusion/external.py:138 in get_eps                                      │
│                                                                                                  │
│   135 │   │   super().__init__(model, model.alphas_cumprod, quantize=quantize)                   │
│   136 │                                                                                          │
│   137 │   def get_eps(self, *args, **kwargs):                                                    │
│ ❱ 138 │   │   return self.inner_model.apply_model(*args, **kwargs)                               │
│   139                                                                                            │
│   140                                                                                            │
│   141 class DiscreteVDDPMDenoiser(DiscreteSchedule):                                             │
│                                                                                                  │
│ /content/ControlNet/cldm/cldm.py:381 in apply_model                                              │
│                                                                                                  │
│   378 │   │   │   if self.global_average_pooling:                                                │
│   379 │   │   │   │   control = [torch.mean(c, dim=(2, 3), keepdim=True) for c in control]       │
│   380 │   │                                                                                      │
│ ❱ 381 │   │   eps = diffusion_model(x=x_noisy, timesteps=t, context=cond_txt, control=control,   │
│   382 │   │                                                                                      │
│   383 │   │   return eps                                                                         │
│   384                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1194 in _call_impl            │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│ in cldm_forward:632                                                                              │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1194 in _call_impl            │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /content/stablediffusion/ldm/modules/diffusionmodules/openaimodel.py:84 in forward               │
│                                                                                                  │
│    81 │   │   │   if isinstance(layer, TimestepBlock):                                           │
│    82 │   │   │   │   x = layer(x, emb)                                                          │
│    83 │   │   │   elif isinstance(layer, SpatialTransformer):                                    │
│ ❱  84 │   │   │   │   x = layer(x, context)                                                      │
│    85 │   │   │   else:                                                                          │
│    86 │   │   │   │   x = layer(x)                                                               │
│    87 │   │   return x                                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1194 in _call_impl            │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /content/stablediffusion/ldm/modules/attention.py:352 in forward                                 │
│                                                                                                  │
│   349 │   │   if self.use_linear:                                                                │
│   350 │   │   │   x = self.proj_in(x)                                                            │
│   351 │   │   for i, block in enumerate(self.transformer_blocks):                                │
│ ❱ 352 │   │   │   x = block(x, context=context[i])                                               │
│   353 │   │   if self.use_linear:                                                                │
│   354 │   │   │   x = self.proj_out(x)                                                           │
│   355 │   │   x = rearrange(x, 'b (h w) c -> b c h w', h=h, w=w).contiguous()                    │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1194 in _call_impl            │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /content/./stablediffusion/modules/sd_hijack_checkpoint.py:4 in BasicTransformerBlock_forward    │
│                                                                                                  │
│    1 from torch.utils.checkpoint import checkpoint                                               │
│    2                                                                                             │
│    3 def BasicTransformerBlock_forward(self, x, context=None):                                   │
│ ❱  4 │   return checkpoint(self._forward, x, context)                                            │
│    5                                                                                             │
│    6 def AttentionBlock_forward(self, x):                                                        │
│    7 │   return checkpoint(self._forward, x)                                                     │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:249 in checkpoint              │
│                                                                                                  │
│   246 │   │   raise ValueError("Unexpected keyword arguments: " + ",".join(arg for arg in kwar   │
│   247 │                                                                                          │
│   248 │   if use_reentrant:                                                                      │
│ ❱ 249 │   │   return CheckpointFunction.apply(function, preserve, *args)                         │
│   250 │   else:                                                                                  │
│   251 │   │   return _checkpoint_without_reentrant(                                              │
│   252 │   │   │   function,                                                                      │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:107 in forward                 │
│                                                                                                  │
│   104 │   │   ctx.save_for_backward(*tensor_inputs)                                              │
│   105 │   │                                                                                      │
│   106 │   │   with torch.no_grad():                                                              │
│ ❱ 107 │   │   │   outputs = run_function(*args)                                                  │
│   108 │   │   return outputs                                                                     │
│   109 │                                                                                          │
│   110 │   @staticmethod                                                                          │
│                                                                                                  │
│ /content/stablediffusion/ldm/modules/attention.py:290 in _forward                                │
│                                                                                                  │
│   287 │   │   return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoin   │
│   288 │                                                                                          │
│   289 │   def _forward(self, x, context=None):                                                   │
│ ❱ 290 │   │   x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else Non   │
│   291 │   │   x = self.attn2(self.norm2(x), context=context) + x                                 │
│   292 │   │   x = self.ff(self.norm3(x)) + x                                                     │
│   293 │   │   return x                                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1194 in _call_impl            │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /content/./stablediffusion/modules/sd_hijack_optimizations.py:82 in                              │
│ split_cross_attention_forward                                                                    │
│                                                                                                  │
│    79 │   q_in = self.to_q(x)                                                                    │
│    80 │   context = default(context, x)                                                          │
│    81 │                                                                                          │
│ ❱  82 │   context_k, context_v = hypernetwork.apply_hypernetwork(shared.loaded_hypernetwork, c   │
│    83 │   k_in = self.to_k(context_k)                                                            │
│    84 │   v_in = self.to_v(context_v)                                                            │
│    85                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
NameError: name 'hypernetwork' is not defined

**Comment by galileostarlight** [comment]
I have a similar issue.

**Comment by Sxela** [comment]
Yep, it fails to load xfomers and falls back to the piece of code that was meant to give an error, as without xformers (or other attention hacks) it was unusable back then. 
You can remove that line and just put the context directly there 
```k_in = self.to_k(context)
    v_in = self.to_v(context)```
