### ISSUE TITLE
Running entirely offline?

### ISSUE THREAD

**Issue by crowbait** [Sxela/WarpFusion#60]
Is it possible to run WarpFusion entirely on my local machine, eg. without the need to involve Collab?

If not, I'd like to suggest that feature. If I understand correctly, the entire processing is done locally anyways, so it would be a matter of "just" providing a local interface. What's so great about current AI tools is, that they can run just on the local machine and always WILL, without relying on external services and platforms which may or may not exist in the future and may or may not remain free and accessible. Having a completely locally-running software guarantees that it will always be accessible and usable.

**Comment by DaBlitzStein** [comment]
+1

**Comment by Sxela** [comment]
You can run in jupyter/vscode locally (after initial install downloads everything), but it will look messy.

**Comment by kevinkazzo** [comment]
I dont get why you would take this much effort to build something in jupyter notebook LOL

dont be surprised if people open source this to be used with streamlit/gradio....its in the works.

**Comment by crowbait** [comment]
Thank you @Sxela
