### ISSUE TITLE
  if flow_save_img_preview or i in range(0,len(ds),len(ds)//10):

### ISSUE THREAD

**Issue by nimnim111** [Sxela/WarpFusion#63]
/content//videoFrames_out_flo_fwd/1024_1920/

Downloading: "https://download.pytorch.org/models/raft_large_C_T_SKHT_V1-0b8c9e55.pth" to /root/.cache/torch/hub/checkpoints/raft_large_C_T_SKHT_V1-0b8c9e55.pth

0%
0/5 [00:03<?, ?it/s]

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

[<ipython-input-19-158c18cbf876>](https://localhost:8080/#) in <cell line: 229>()
    277           p = Pool(threads)
    278           for i,batch in enumerate(tqdm(dl)):
--> 279               flow_batch(i, batch, p)
    280           p.close()
    281           p.join()

[<ipython-input-19-158c18cbf876>](https://localhost:8080/#) in flow_batch(i, batch, pool)
    172           flow21 = flow21[0].permute(1, 2, 0).detach().cpu().numpy()
    173 
--> 174           if flow_save_img_preview or i in range(0,len(ds),len(ds)//10):
    175             pool.apply_async(save_preview, (flow21, out_flow21_fn+'.jpg') )
    176           pool.apply_async(np.save, (out_flow21_fn, flow21))

ValueError: range() arg 3 must not be zero

**Comment by Sxela** [comment]
You have <10 frames extracted from your video. This means you either manually did that by settings end_frame too low, or the video path was wrong, and no frames were extracted at all.
