### ISSUE TITLE
Is it possible to use this without being a patreon supporter?

### ISSUE THREAD

**Issue by yratof** [Sxela/WarpFusion#67]
I've got a few friends who'd like to try this out and I can see that 0.9 is available in the releases tab. Is it ok to point them to this github and use it? 

I saw that you're up to v0.19 at the moment and Just wanted to check that this isn't wildly outdated and potentially not working

**Comment by Sxela** [comment]
It's outdated if you use it on colab, but that can be fixed with minor dependency adjustments if you encounter errors.

**Comment by Sxela** [comment]
Check the latest version here once in a while, It's getting updated much faster now, v0.10 is already here, and v0.11 coming next week, and that is the version people were already making tutorials for.

**Comment by yratof** [comment]
And I can share this freely with a community of makers to play with it?On 19 Aug 2023, at 14:25, Alex ***@***.***> wrote:﻿
Check the latest version here once in a while, It's getting updated much faster now, v0.10 is already here, and v0.11 coming next week, and that is the version people were already making tutorials for.

**Comment by Sxela** [comment]
The version you get here? Sure

**Comment by Sxela** [comment]
https://github.com/Sxela/WarpFusion/branches - you can check for new versions here and here https://github.com/Sxela/WarpFusion/releases
