### ISSUE TITLE
How does warpfusion work?

### ISSUE THREAD

**Issue by alexblattner** [Sxela/WarpFusion#68]
Hi, I haven't seen any explanation about warpfusion beyond "it does animation and here's how to use it for it". What does it do though? What method does it use to create animations?

**Comment by ZachAR3** [comment]
Close your issue, this is not an appropriate place to ask this. Go ask in the discord server or watch some YT videos on it.

**Comment by alexblattner** [comment]
@ZachAR3 how is that not appropriate? I am literally asking about how this functions from a technical standpoint and I am sure others would like an explanation too.

**Comment by ZachAR3** [comment]
> @ZachAR3 how is that not appropriate? I am literally asking about how this functions from a technical standpoint and I am sure others would like an explanation too.

This is a Github issue tracker not a Q&A. Email the dev or ask ON THE DISCORD, as previously mentioned, Github isn't for asking questions. (Unless in the discussions area which this project doesn't have)

**Comment by alexblattner** [comment]
@ZachAR3 github issues can be used for this and has been many times in the past in many popular repos. I don't see why this is such an issue.

**Comment by ZachAR3** [comment]
Because as someone who has made some tools myself I know how annoying it can be to spoon feed answers to people who are too lazy to look it up, or check in the correct channels. Good chance the dev has already answered this if you actually looked, and I know for sure a large amount of the YT vids explain it, and it is explained all the time in the discord.

**Comment by alexblattner** [comment]
@ZachAR3 really? I would love to close this issue if I could get an answer to my question :)

**Comment by Sxela** [comment]
Quote from the first page of the notebook: 

> Init warping
> The feature works like this: we take the 1st frame, diffuse it as usual as an image input with fixed skip steps. Then we warp it with its flow map into the 2nd frame and blend it with the original raw video 2nd frame. This way we get the style from heavily stylized 1st frame (warped accordingly) and content from 2nd frame (to reduce warping artifacts and prevent overexposure)

**Comment by ZachAR3** [comment]
> @Sxela thanks for that! I didn't see an official notebook, just steps on how to run things on a notebook in general. This is helpful, but not very precise. -How many steps are skipped? If it's not constant, what's the logic? -When you talk about a frame, what do you mean exactly? A picture? Half a picture? Something else entirely? -When you talk about flow map, do you mean this: https://arxiv.org/pdf/2305.03989.pdf
> 
> Is there a way to see the code without dockers?
> 
> Thank you very much for taking the time to answer

All of the code specific to WarpFusion is visible in it's IPYNB file. You're questions also make literally no since. 
- Nothing is skipped? It just takes the frame information from the last generated image for the styling, and using one of the control net methods + the flow map uses it to generate the next frame. 
- The frame is literally the image... 
- The flow map is just the info gotten from the previous frame about composition and object positions, yes it is from the paper you linked I believe. Now please close this waste of an issue...

**Comment by alexblattner** [comment]
@ZachAR3 
May I have a link to the IPYNB file? I didn't see it anywhere in the repository.
-it literally says "fixed skip steps". The rest of the info you wrote was not evident. I think that having the link to the actual code would be best to solve the problem.
-I was asking because I was wondering if it used temporal gen perhaps
-wouldn't it have been faster to give me something like the paper instead of being salty?

I'll close the issue when I get the link to the IPYNB file and write for the rest of the community how it works after analyzing the code so the answer is out there for the future.

**Comment by ZachAR3** [comment]
> @ZachAR3 May I have a link to the IPYNB file? I didn't see it anywhere in the repository. -it literally says "fixed skip steps". The rest of the info you wrote was not evident. I think that having the link to the actual code would be best to solve the problem. -I was asking because I was wondering if it used temporal gen perhaps -wouldn't it have been faster to give me something like the paper instead of being salty?
> 
> I'll close the issue when I get the link to the IPYNB file and write for the rest of the community how it works after analyzing the code so the answer is out there for the future.

My bad about skip steps, the IPYNB files are in the version specific branches, not master.

**Comment by alexblattner** [comment]
@ZachAR3 thanks for letting me know about the code.

HOLY SHIT! How many lines of code is that?! 

@Sxela any plans to do something similar for diffusers by any chance? I would be down to pay for a deep dive into your code too but there's no way to contact you beyond here and twitter

**Comment by ZachAR3** [comment]
> @ZachAR3 thanks for letting me know about the code.
> 
> HOLY SHIT! How many lines of code is that?!
> 
> @Sxela any plans to do something similar for diffusers by any chance? I would be down to pay for a deep dive into your code too but there's no way to contact you beyond here and twitter

LMFAO, a lot of it is formatting. But yeah, it's not something that easy to 

> analyzing the code so the answer is out there for the future.

**Comment by Sxela** [comment]
I'd suggest checking the readme and tutorials, and spinning the latest public version on colab. 
You can check this vid for a comfyui-based explanation of the main loop 

https://www.youtube.com/watch?v=ZuPBDRjwtu0&list=PL2cEnissQhlCko-T3gPH9ltMLMRjabpIS&index=2&ab_channel=DerpLearning
