### ISSUE TITLE
Linux Anaconda environment setup

### ISSUE THREAD

**Issue by ZachAR3** [Sxela/WarpFusion#74]
I remade the  .bat scripts for environment setup and running of the app, the only part that I can't get to function but that doesn't seem to affect functionality is enabling "jupyter_http_over_ws" with `jupyter serverextension enable --py jupyter_http_over_ws".`
Ignoring that do you want me to add them into my existing PR for ease of use on Linux?

run_relative.sh
```
#!/bin/sh
echo Launching jupyter server.
echo -----
echo After the server has launched, go to https://colab.research.google.com
echo Click File -> Upload Notebook and upload the *.ipynb file
echo Click on the dropdown menu near "Connect" or "Reconnect" button on the topright part of the interface.
echo Select "connect to a local runtime" and paste the URL that will be generated below.
echo which looks like "http://localhost:8888/?token=somenumbers"
echo Click "Connect" and CTRL+F9 to run all cells.
echo ------
# A fix for https://github.com/conda/conda/issues/7980
eval "$(conda shell.bash hook)"
conda activate ./env
jupyter notebook ./ --NotebookApp.allow_origin='https://colab.research.google.com' --port=8888 --NotebookApp.port_retries=0
echo Notebook successfully launched
```

prepare_env_relative.sh
```
#!/bin/sh
echo Creating python 3.10 environment "env"
# A fix for https://github.com/conda/conda/issues/7980
eval "$(conda shell.bash hook)"
conda create --prefix env python=3.10.9 -y
conda activate ./env
conda install entrypoints=0.4 ipython=8.10.0 jupyter_client=7.4.9 jupyter_core=5.2.0 packaging=22.0 sqlite=3.40.1 tzdata=2022g --force-reinstall -y
conda install ipykernel -y
python -m ipykernel install --user
pip install jupyter_http_over_ws
echo Environment created. Run "conda activate ./env inside this folder to enable it."
```

**Comment by Sxela** [comment]
Check the pr adding jupyter-notebook install here - #71

**Comment by ZachAR3** [comment]
> Check the pr adding jupyter-notebook install here - #71

I know the Docker files exist, but many prefer to use Python envs or conda since it is a lot smaller generally and easier to configure IMO. If you don't think it's needed though I can close this issue.

**Comment by dsalvat1** [comment]
If I have time, I may add to this effort. But remember, not only are we talking python. There are also CUDA driver versions and other dependencies that will impact your Linux server, not every box is the same. Docker (and maybe in the future Kubernetes if time permits) is just a way to containerize these changes.

**Comment by ZachAR3** [comment]
> If I have time, I may add to this effort. But remember, not only are we talking python. There are also CUDA driver versions and other dependencies that will impact your Linux server, not every box is the same. Docker (and maybe in the future Kubernetes if time permits) is just a way to containerize these changes and uses an optimized Nvidia Linux Image prebuilt (basically a stripped down version of ubuntu with cuda drivers)
> 
> Also, the docker container is literally using python venv

Gotcha, fair enough then. And again, it being in docker is a hassle since it's running its own little system and takes a bunch of uneeded space to do so. I think the script should be available, and just warn for incompatibilities with Cuda versions and such. Altough I do understand not wanting to deal with trouble shooting so fair enough if you wanna leave it as docker only on Linux.

**Comment by Sxela** [comment]
> > Check the pr adding jupyter-notebook install here - #71
> 
> I know the Docker files exist, but many prefer to use Python envs or conda since it is a lot smaller generally and easier to configure IMO. If you don't think it's needed though I can close this issue.

I meant that you can use that newly added dependency in your shell script

**Comment by ZachAR3** [comment]
> If I have time, I may add to this effort. But remember, not only are we talking python. There are also CUDA driver versions and other dependencies that will impact your Linux server, not every box is the same. Docker (and maybe in the future Kubernetes if time permits) is just a way to containerize these changes and uses an optimized Nvidia Linux Image prebuilt (basically a stripped down version of ubuntu with cuda drivers)
> 
> Also, the docker container is literally using python venv

Gotcha, fair enough then. And again, it being in docker is a hassle since it's running its own little system and takes a bunch of uneeded space to do so. I think the script should be available, and just warn for incompatibilities with Cuda versions and such. Altough I do understand not wanting to deal with trouble shooting so fair enough if you wanna leave it as docker only on Linux.

**Comment by dsalvat1** [comment]
@ZachAR3 I have created a script for you to test. It is specific to ubuntu 22.04 you must have the CUDA drivers and toolkit installed and I would stay clear from troubleshooting cuda for less experienced users.

Min Requirements or you won't get this running:
- Basic knowledge on Ubuntu and Python venv
- Clean ubuntu environment: sudo apt remove python-pip python3-pip --purge
- rm -rf or mv ~/.cache

I decided to stick with python venv instead of Anaconda because it is more user friendly and easier to deploy

The instructions used for windows should suffice, with the only difference that this script creates a directory called "WarpFusion{version}", "version" that you can input during setup to keep your environment separated. Script also checks for preinstalled packages and modules. You can improve it.

Test it out and submit it to the repo for @Sxela's approval (can I get free Patreon access? :D ) .

![image](https://github.com/Sxela/WarpFusion/assets/9200806/2fa7678b-5cac-4e9d-9a6b-f786a6d93a3f)

![image](https://github.com/Sxela/WarpFusion/assets/9200806/df77c7f7-8aa3-47f6-9e50-ebb038172a3f)

[linux_install.zip](https://github.com/Sxela/WarpFusion/files/12838780/linux_install.zip)

**Comment by dsalvat1** [comment]
My setup:

Ubuntu 22.04 - Pure command line, no GUI
0:00.0 Host bridge: Intel Corporation 8th/9th Gen Core 8-core Desktop Processor Host Bridge/DRAM Registers [Coffee Lake S] (rev 0d)
00:01.0 PCI bridge: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) (rev 0d)
00:01.1 PCI bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x8) (rev 0d)
00:12.0 Signal processing controller: Intel Corporation Cannon Lake PCH Thermal Controller (rev 10)
00:14.0 USB controller: Intel Corporation Cannon Lake PCH USB 3.1 xHCI Host Controller (rev 10)
00:14.2 RAM memory: Intel Corporation Cannon Lake PCH Shared SRAM (rev 10)
00:16.0 Communication controller: Intel Corporation Cannon Lake PCH HECI Controller (rev 10)
00:17.0 SATA controller: Intel Corporation Cannon Lake PCH SATA AHCI Controller (rev 10)
00:1b.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #17 (rev f0)
00:1c.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #1 (rev f0)
00:1d.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #9 (rev f0)
00:1f.0 ISA bridge: Intel Corporation Z390 Chipset LPC/eSPI Controller (rev 10)
00:1f.3 Audio device: Intel Corporation Cannon Lake PCH cAVS (rev 10)
00:1f.4 SMBus: Intel Corporation Cannon Lake PCH SMBus Controller (rev 10)
00:1f.5 Serial bus controller: Intel Corporation Cannon Lake PCH SPI Controller (rev 10)
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (7) I219-V (rev 10)
02:00.0 VGA compatible controller: NVIDIA Corporation Device 2782 (rev a1)
02:00.1 Audio device: NVIDIA Corporation Device 22bc (rev a1)
05:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983

Using mobaXterm to ssh and forward port 8888 to my windows station.

The ubuntu workstation is only used for my ML experiments and playing with video rendering. :D

**Comment by dsalvat1** [comment]
Before I forget, he is the run_linux.sh file to start jupyter again. Just drop it inside the warp{version} folder
[run_linux.zip](https://github.com/Sxela/WarpFusion/files/12839001/run_linux.zip)

**Comment by dsalvat1** [comment]
Submitted the script via PR tonight, you are welcome to use it to create a conda version or improve it.

**Comment by ZachAR3** [comment]
> @ZachAR3 I have created a script for you to test. It is specific to ubuntu 22.04 you must have the CUDA drivers and toolkit installed and I would stay clear from troubleshooting cuda for less experienced users.
> 
> Min Requirements or you won't get this running:
> 
>     * Basic knowledge on Ubuntu and Python venv
> 
>     * Clean ubuntu environment: sudo apt remove python-pip python3-pip --purge
> 
>     * rm -rf or mv ~/.cache
> 
> 
> I decided to stick with python venv instead of Anaconda because it is more user friendly and easier to deploy
> 
> The instructions used for windows should suffice, with the only difference that this script creates a directory called "WarpFusion{version}", "version" that you can input during setup to keep your environment separated. Script also checks for preinstalled packages and modules. You can improve it.
> 
> Test it out and submit it to the repo for @Sxela's approval (can I get free Patreon access? :D ) .
> 
> ![image](https://user-images.githubusercontent.com/9200806/273404844-2fa7678b-5cac-4e9d-9a6b-f786a6d93a3f.png)
> 
> ![image](https://user-images.githubusercontent.com/9200806/273405913-df77c7f7-8aa3-47f6-9e50-ebb038172a3f.png)
> 
> [linux_install.zip](https://github.com/Sxela/WarpFusion/files/12838780/linux_install.zip)

I run Arch so I can't run ubuntu specific scripts saddly.

**Comment by dsalvat1** [comment]
@ZachAR3 if I recall correctly the only lines that are distribution specific are 13 through 16. 

Unfortunately I never got around using arch, I only have experience with Redhat, Suse, and Slackware.

I recommend running it on your end for validation by commenting out those lines. 

Considering you're using ARCH Linux, you might want to add an OS detection feature along with conditionals to include your ARCH-specific repositories.

**Comment by ZachAR3** [comment]
Gotcha, I updated it now to work with your Ubuntu or Arch with auto detection. Why do you ask for a version just as the install folder though? That makes it seem like its gonna install that version IMO, maybe rename to folder name or have it auto use the latest version name if no folder exists with that name? I am trying the script RN on arch but its gonna take a while to download everything in it haha. If all works well and the naming of version is cleared up I will make a PR with the Arch congruent script.

**Comment by ZachAR3** [comment]
Gotcha, I updated it now to work with your Ubuntu or Arch with auto detection. Why do you ask for a version just as the install folder though? That makes it seem like its gonna install that version IMO, maybe rename to folder name or have it auto use the latest version name if no folder exists with that name? I am trying the script RN on arch but its gonna take a while to download everything in it haha. If all works well and the naming of version is cleared up I will make a PR with the Arch congruent script.

**Comment by dsalvat1** [comment]
@ZachAR3 - The reason for "versioning" each folder is something I can across windows users in discourse. Many folks test Sxela's different notebooks that he publishes for his paid tier. 

In my experience, keeping your working environment separate, nice and clean can help solve problem's easier that tried to run different notebooks with different requirements (or new features) on the same virtual environments.
