### ISSUE TITLE
Create a video does not work sometimes on collab

### ISSUE THREAD

**Issue by giorgosn** [Sxela/WarpFusion#78]
Hi! I am experimenting with the project and I have noticed this probbly bug.
I follow the instructions from https://www.youtube.com/watch?v=m8xaPnaooyg&t=939s
and when I generate the frames after some time seems to try and run the next block ( but I verify that still generates photos in the background) and fails....
After a while if I try to run the next block "Create the video" I generate some seconds but not whole the video.
Also getting this error:
![image](https://github.com/Sxela/WarpFusion/assets/13453884/592c9ffc-79b3-46c6-8895-ae7964ff8a3c)

Any ideas what I can do?

**Comment by Sxela** [comment]
You need to run all cells for that, you can enable the "skip diffusion" checkbox to skip the render and go to video export
